# .github/workflows/test01.yaml
name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # - name: Install chrome
      #   run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: Install the necessary packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the PytTest script
        run: pytest -rA 
